LayerManager/layman

- Pipfile
- Pipfile.lock
- doc/dependencies.md
- src/clear_layman_data.py
- src/layman/cache/mem.py
- src/layman/cache/mem_redis.py
- src/layman/celery.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/sld.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/geoserver/util.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/rest_layer.py
- src/layman/layer/rest_layers.py
- src/layman/layer/rest_test.py
- src/layman/make_celery.py
- src/layman/map/rest_test.py
- src/layman_settings.py
> Use mem_redis cache for GeoServer's WMS/WFS Capabilities

- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
> Fix currently_changing of WMS and WFS cache

- src/layman/layer/geoserver/util.py
See https://github.com/geopython/OWSLib/issues/673
> Simplify WFS proxy after upgrade to OWSLib 0.20

- .env.demo
- .env.dev
- .env.test
- .travis.yml
- CHANGELOG.md
- Makefile
- README.md
- deps/geoserver/docker/.env
- deps/geoserver/docker/code/reset-default-layman-datadir.sh
- doc/env-settings.md
- docker-compose.deps.demo.yml
- docker-compose.deps.yml
- src/clear_layman_data.py
- src/layman/__init__.py
- src/layman/common/geoserver/__init__.py
- src/layman/common/geoserver/geoserver_test.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/util.py
- src/layman_settings_demo.py
- src/layman_settings_dev.py
- src/layman_settings_test.py
- src/wait_for_deps.py
> Adjust GeoServer at Layman startup

- src/layman/common/geoserver/__init__.py
- src/layman/map/rest_test.py
> Fix minor errors

- CHANGELOG.md
- src/layman/layer/db/__init__.py
- src/layman/layer/rest_test.py
> geometry-layer-type

- .travis.yml
- Makefile
- src/assert_db.py
- src/layman/authn/oauth2_test.py
- src/layman/common/language.py
- src/layman/common/metadata.py
- src/layman/common/micka/util.py
- src/layman/layer/db/__init__.py
- src/layman/layer/db/table.py
- src/layman/layer/filesystem/input_file_test.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/micka/util_test.py
- src/layman/layer/rest_layers.py
- src/layman/layer/rest_test.py
- src/layman/map/micka/util_test.py
- src/layman/map/rest_maps.py
- src/layman/map/rest_test.py
- src/refresh-doc-metadata-xpath.py
- test/process.py
> Code style improvements part 2

- CHANGELOG.md
- doc/rest.md
- src/layman/common/util.py
- src/layman/layer/db/table.py
- src/layman/layer/filesystem/input_chunk.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/input_sld.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman/layer/filesystem/uuid.py
- src/layman/layer/geoserver/sld.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/micka/csw.py
- src/layman/layer/micka/csw_test.py
- src/layman/layer/micka/soap.py
- src/layman/layer/rest_layers.py
- src/layman/layer/rest_layers_test.py
- src/layman/layer/rest_test.py
- src/layman/layer/util.py
- src/layman/map/filesystem/input_file.py
- src/layman/map/filesystem/thumbnail.py
- src/layman/map/filesystem/uuid.py
- src/layman/map/micka/csw.py
- src/layman/map/micka/soap.py
- src/layman/map/rest_maps.py
- src/layman/map/rest_maps_test.py
- src/layman/map/util.py
- test/flask_client.py
- test/process_client.py
> Title in get layers and get maps

- Makefile
- docker-compose.test.yml
- ensure-test-data.sh
- start.sh
- test.sh
Also fixes #81 by
- downloading test data before celery_worker_test starts
- delaying start of celery_worker_test as long as possible
~~It's expected that test will not pass right now, because naturalearth download is [currently broken](https://github.com/nvkelso/natural-earth-vector/issues/416). This PR should wait till it will be fixed.~~
Natural Earth download is fixed. tests pass again.
> Improve bash commands, extract ensure-test-data.sh from test.sh

- .env.demo
- .env.dev
- .env.test
- .travis.yml
- CHANGELOG.md
- Makefile
- doc/env-settings.md
> Release 1.7.0 last changes

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- src/layman/layer/geoserver/sld.py
- src/layman/layer/rest_layer_style.py
- src/layman/layer/rest_layers.py
- src/layman/map/rest_maps.py
- Use Layman Test Client v1.3.0
- #109 Handle records without title in GET Layers / GET Maps
- Return real SLD style in GET Layer Style instead of just metadata
> Release 1.7.1

- .travis.yml
- Makefile
- src/layman/gs_wfs_proxy.py
- src/layman/gs_wfs_proxy_test.py
- src/layman/map/prime_db_schema/table.py
- test/data/wfs.py
- test/flask_client.py
- test/process.py
Should be ready for rebase, not squash
> Various minor improvements and bug fixes

- test/process.py
- test/process_client.py
…er methods for process client.
> Create process client decorator, improve publish/patch/delete map/layer methods for process client.

- CHANGELOG.md
- src/layman/map/rest_maps.py
- src/layman/map/rest_maps_test.py
> Test and repair url in get.maps

- src/layman/authz/authz_test.py
- src/layman/layer/rest_layer_patch_test.py
- test/process.py
- test/process_client.py
> Test env. variables for using public workspaces

- src/geoserver/authn.py
- src/layman/authz/util.py
- src/layman/celery_test.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/util.py
- src/layman/gs_wfs_proxy.py
- src/layman/gs_wfs_proxy_test.py
- src/layman/layer/client_test.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman/layer/geoserver/util.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/rest_layer_style_test.py
- src/layman/layer/util.py
- src/layman/map/rest_test.py
- src/layman/map/util.py
- src/layman/user/rest_users_test.py
- src/layman/util.py
- src/layman/util_test.py
- test/flask_client.py
- test/process_client.py
> Miscellaneous commits

- src/geoserver/authn.py
- src/layman_settings.py
- src/setup_gs_auth.py
> GeoServer HTTP header filter chain is used also for wms and ows

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- Makefile
- deps/nginx/sample/nginx-template
- deps/nginx/sample/nginx.conf
- doc/env-settings.md
- doc/security.md
- docker-compose.demo.yml
- src/layman/authn/http_header/__init__.py
- src/layman/authn/http_header/http_header_test.py
- src/layman/common/geoserver/__init__.py
- src/layman/error_list.py
- src/layman/gs_wfs_proxy_test.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman_settings.py
- test/process.py
- test/process_client.py
> HTTP Header authentication

- CHANGELOG.md
- doc/rest.md
- doc/security.md
- src/layman/authz/__init__.py
- src/layman/common/redis.py
- src/layman/layer/rest_layer_patch_test.py
- src/layman/layer/rest_layers.py
- src/layman/layer/rest_layers_test.py
- src/layman/layer/rest_test.py
- src/layman/map/rest_maps.py
- src/layman/map/rest_maps_test.py
- src/layman/rest_multipublication_test.py
- src/layman/util.py
- src/layman/util_test.py
- test/process.py
- test/process_client.py
For rebase and merge. Go per commit.
> Rest endpoint for mass deletion

- doc/data-storage.md
- doc/endpoints.md
- doc/security.md
Waits for https://github.com/jirik/layman/tree/rest-endpoint-for-mass-deletion to be merged
> Improve documentation related to authorization, WMS and WFS

- src/layman/common/prime_db_schema/publications.py
- src/layman/layer/db/table.py
- src/layman/layer/filesystem/input_chunk.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/input_sld.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman/layer/filesystem/uuid.py
- src/layman/layer/geoserver/sld.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/micka/soap.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/layer/rest_layer.py
- src/layman/layer/rest_layer_test.py
- src/layman/layer/rest_layers.py
- src/layman/layer/util.py
- src/layman/map/filesystem/input_file.py
- src/layman/map/filesystem/thumbnail.py
- src/layman/map/filesystem/uuid.py
- src/layman/map/micka/soap.py
- src/layman/map/prime_db_schema/table.py
- src/layman/map/rest_map.py
- src/layman/map/rest_maps.py
- src/layman/map/util.py
- src/layman/rest_publication_test.py
- src/layman/util_test.py
- test/process_client.py
> Bug 172 - already exists layer

- src/layman/authz/__init__.py
- src/layman/common/filesystem/uuid.py
- src/layman/common/micka/csw-number-of-records-template.xml
- src/layman/common/micka/soap-insert-template.xml
- src/layman/common/micka/util.py
- src/layman/layer/micka/csw.py
- src/layman/layer/micka/soap.py
- src/layman/layer/micka/tasks.py
- src/layman/map/micka/soap.py
- src/layman/map/micka/tasks.py
- src/layman/rest_publication_test.py
- test/process.py
- test/process_client.py
> Adjust Micka metadata record public visibility

- src/layman/authn/oauth2/util.py
- src/layman/authn/oauth2_test.py
Review after https://github.com/jirik/layman/pull/202
> Make AuthorizationIssUrl header optional for OAuth2

- .github/workflows/code_quality.yml
- doc/dependencies.md
- docker-compose.test.yml
- docker/Pipfile
- docker/Pipfile.lock
- pytest.ini
- src/layman/authz/authz_env_test.py
- src/layman/authz/authz_test.py
- src/layman/celery_test.py
- src/layman/common/geoserver/__init__.py
- src/layman/common/micka/util.py
- src/layman/common/prime_db_schema/util.py
- src/layman/layer/db/__init__.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/sld.py
- src/layman/layer/geoserver/util.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/rest_publication_test.py
- test/process_client.py
> Test improvements

- Makefile
- src/geoserver/epsg_properties.py
- src/setup_geoserver.py
> Propagate OUTPUT_SRS_LIST to GeoServer epsg.properties

- deps/nginx/sample/nginx-template
> Make flower accessible in demo configuration

- CHANGELOG.md
- src/layman/common/prime_db_schema/migrate_test.py
- src/layman/error_list.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/geoserver_test.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_10.py
- src/layman/upgrade/upgrade_v_10_test.py
- test/process.py
- test/process_client.py
Per commit:
- [o] Layman Test Client
- [o] Documentation
> Wms workspace migrations

- CHANGELOG.md
- doc/rest.md
- src/layman/common/geoserver/__init__.py
- src/layman/common/prime_db_schema/migrate_test.py
- src/layman/layer/geoserver/sld.py
- src/layman/layer/geoserver/sld_test.py
- src/layman/layer/util.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_10.py
- src/layman/upgrade/upgrade_v_10_test.py
- test/process_client.py
- test/util.py
> Migration of layers into dedicated WMS GeoServer workspace

- CHANGELOG.md
- doc/metadata.md
- src/layman/common/micka/util.py
- src/layman/layer/micka/csw.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_10.py
- src/layman/upgrade/upgrade_v1_10_test.py
- src/layman/upgrade/upgrade_v1_10_test_layer_metadata.xml
- test/process_client.py
> Migrate layer metadata

- docker-compose.deps.yml
- src/layman/error_list.py
- src/layman/layer/db/__init__.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/qgis/layer-template.qml
- src/layman/layer/qgis/project-template.qgs
- src/layman/layer/qgis/util.py
- src/layman/layer/qgis/util_test.py
- src/layman/layer/qgis/wms.py
- src/layman_settings.py
> Fill QML to QGS template

- CHANGELOG.md
- doc/data-storage.md
- doc/models.md
- doc/rest.md
> Documentation for QGIS WMS layers

- CHANGELOG.md
- src/layman/__init__.py
- src/layman/common/output_srs_list_test.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/layer/empty_bbox_test.py
- src/layman/layer/qgis/output_srs.py
- src/layman/layer/qgis/tasks.py
- src/layman/layer/qgis/util.py
- src/layman/layer/qgis/wms.py
- src/layman/util.py
> Qgis output srs list

- src/layman/__init__.py
- src/layman/layer/qgis/output_srs.py
> Better logging for ensuring output SRS list for QGIS projects

- CHANGELOG.md
- doc/rest.md
- sample/data/geometry-types/all.geojson
- sample/data/geometry-types/line.qml
- sample/data/geometry-types/linestring.geojson
- sample/data/geometry-types/point.geojson
- sample/data/geometry-types/point.qml
- sample/data/geometry-types/polygon.geojson
- sample/data/geometry-types/polygon.qml
- src/layman/common/db/__init__.py
- src/layman/common/geoserver/__init__.py
- src/layman/layer/qgis/util.py
> Qgis launder attribute names

- sample/style/ne_10m_admin_0_countries.qml
- src/layman/layer/qgis/util.py
- src/layman/layer/qgis/util_test.py
> Copy root attributes from QML to QGIS project

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/qgis/qml-template.qml
- src/layman/layer/qgis/util.py
- src/layman/layer/qgis/util_test.py
- src/layman/layer/qgis/wms.py
- src/layman/layer/rest_layer_style.py
- src/layman/layer/rest_layer_style_test.py
> Qgis get layer style

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- doc/async-file-upload.md
- doc/models.md
- doc/rest.md
- pytest.ini
- src/layman/__init__.py
- src/layman/authn/oauth2_test.py
- src/layman/authz/authz_test.py
- src/layman/common/rest.py
- src/layman/common/rest_test.py
- src/layman/layer/client_test.py
- src/layman/layer/micka/util_test.py
- src/layman/layer/micka/util_test_filled_template.xml
- src/layman/layer/rest_test.py
- src/layman/layer/rest_test_filled_template.xml
- src/layman/map/client_test.py
- src/layman/map/micka/record-template-filled.xml
- src/layman/map/micka/util_test.py
- src/layman/map/micka/util_test_filled_template.xml
- src/layman/map/rest_maps_test.py
- src/layman/map/rest_test.py
- src/layman/map/rest_test_filled_template.xml
- src/layman/upgrade/upgrade_v1_10_test.py
- src/layman/upgrade/upgrade_v1_10_test_layer_metadata.xml
- src/layman/util_test.py
- test/flask_client.py
> Workspace centric api2

- src/layman/layer/micka/csw.py
- src/layman/map/micka/csw.py
- src/layman/upgrade/upgrade_v1_10.py
- src/layman/upgrade/upgrade_v1_10_test.py
- src/layman/upgrade/upgrade_v1_10_test_layer_metadata.xml
> Workspace centric api metadata

- CHANGELOG.md
- Makefile
- README.md
- deps/nginx/sample/nginx-template
- src/layman/__init__.py
- src/standalone_upgrade.py
> Separated upgrade jirik

- src/layman/layer/rest_test.py
- src/layman/map/rest_test.py
- src/layman/upgrade/upgrade_v1_10_test.py
- src/layman/upgrade/upgrade_v1_9_test.py
> Add delete_layer/delete_map after tests

- src/layman/rest_deprecated_test.py
> Test Link header for deprecated endpoints

- src/layman/__init__.py
- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/geoserver/wms_test.py
- test/geoserver_client.py
> Rename gs_wfs_proxy to geoserver_proxy

- .github/workflows/main.yml
- sample/layman.layer/sample_point_cz_wrong_literal.sld
- src/layman/geoserver_proxy_test.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman/layer/filesystem/thumbnail_test.py
- test/process_client.py
> If layer thumbnail rendering fails, do not save file

- src/layman/common/__init__.py
- src/layman/common/micka/util.py
- src/layman/common/tasks.py
- src/layman/layer/__init__.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/rest_layer_style.py
- src/layman/layer/util.py
- src/layman/map/__init__.py
- src/layman/map/micka/csw.py
- src/layman/map/util.py
- src/layman/util.py
- src/layman/util_auth_test.py
- src/layman/util_test.py
> Improve publication info

- CHANGELOG.md
- src/layman/layer/micka/csw.py
> Fix 1.10.0 upgrade error

- CHANGELOG.md
- src/layman/layer/micka/csw.py
> Upgrade 1.10.0 error DB

- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/layer/rest_layers.py
- src/layman/map/rest_maps.py
- src/layman/util.py
- src/layman_settings.py
- test/process.py
Part of issue #273 
Optionally
> Select publications filter2

- src/layman/authz/__init__.py
- src/layman/common/rest.py
- src/layman/common/rest_test.py
- src/layman/layer/rest_layers.py
- src/layman/map/rest_maps.py
> Publications authorization decorator

- CHANGELOG.md
- src/layman/common/prime_db_schema/migrate_test.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_12.py
Part of issue #257
- ~~Tests~~
> Small improvements related to full-text search

- .env.demo
- .env.dev
- .env.test
- doc/rest.md
- src/layman/common/get_publications_consts.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/common/rest.py
- src/layman/error_list.py
- src/layman/rest_multipublication_test.py
Part of issue #257 
Optionally
> Order by title

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_12.py
- src/layman/upgrade/upgrade_v1_12_test.py
- src/layman/upgrade/upgrade_v1_12_test_layer_metadata.xml
> Migrate layer metadata records: Add LAYERS URL parameter

- src/layman/common/rest.py
- src/layman/rest_multipublication_test.py
> Enable full_text_filter and order_by=full_text

- CHANGELOG.md
- README.md
- doc/rest.md
- src/layman/__init__.py
- src/layman/common/prime_db_schema/migrate_test.py
- src/layman/rest_about.py
- src/layman/rest_about_test.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/consts.py
- src/layman/upgrade/upgrade_test.py
- src/layman/upgrade/upgrade_v1_12.py
- src/layman/upgrade/upgrade_v1_12_test.py
> Pre pre prod fixes

- .env.demo
- .env.dev
- .env.test
- doc/rest.md
- src/layman/common/get_publications_consts.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/common/rest.py
- src/layman/common/rest_test.py
- src/layman/rest_multipublication_test.py
- src/layman/util.py
Part of issue #257 
Optionally
> Pagination

- src/layman/common/prime_db_schema/publications_test.py
- src/layman/rest_multipublication_test.py
- test/prime_db_schema_client.py
> Rest multipublication complex tests

- .env.demo
- .env.dev
- .env.test
- src/layman/layer/rest_workspace_layers.py
- src/layman/map/rest_workspace_maps.py
- src/layman/rest_multipublication_test.py
- test/process_client.py
> Filters for workspace publications

- src/layman/authn/__init__.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/rest.py
- src/layman/geoserver_proxy.py
- src/layman/layer/rest_layers.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/map/filesystem/thumbnail.py
- src/layman/map/rest_maps.py
- src/layman/map/rest_workspace_maps.py
- src/layman/user/util.py
- src/layman_settings.py
> Method get_authn_username returns ANONYM_USER and NONAME_USER instead of None by default

- README.md
…s/335)
Part of issue #335
- ~~Tests~~
Optionally
> Add kernel version requirement

- CHANGELOG.md
- src/geoserver/util.py
- src/layman/common/bbox.py
- src/layman/common/bbox_test.py
- src/layman/common/util.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman/layer/geoserver/sld.py
- src/layman/layer/geoserver/wms.py
- src/layman/map/filesystem/input_file.py
- src/layman/map/filesystem/thumbnail.py
- src/layman/util.py
- src/layman/util_test.py
- src/layman_settings.py
- timgen/index.js
- timgen/src/map.js
> Remove some inter-source dependencies

- .env.test
- src/layman/authn/oauth2_test.py
- src/layman/authz/authz_test.py
- src/layman/layer/client_test.py
- src/layman/layer/geoserver/wms_test.py
- src/layman/layer/micka/util_test.py
- src/layman/layer/micka/util_test_filled_template.xml
- src/layman/layer/qgis/qgis_test.py
- src/layman/layer/rest_test_filled_template.xml
- src/layman/layer/rest_workspace_layer_style_test.py
- src/layman/layer/rest_workspace_layer_test.py
- src/layman/layer/rest_workspace_layers_test.py
- src/layman/layer/rest_workspace_test.py
- src/layman/map/micka/record-template-filled.xml
- src/layman/map/micka/util_test.py
- src/layman/map/micka/util_test_filled_template.xml
- src/layman/map/rest_test_filled_template.xml
- src/layman/map/rest_workspace_maps_test.py
- src/layman/map/rest_workspace_test.py
- src/layman/rest_about_test.py
- src/layman/rest_responses_test.py
- src/layman/upgrade/upgrade_v1_10_test.py
- src/layman/user/rest_users_test.py
- src/layman/util.py
- src/layman/util_test.py
- test/flask_client.py
- test/geoserver_client.py
- test/process_client.py
- test/util.py
> Use different LAYMAN_PROXY_SERVER_NAME in testing

- CHANGELOG.md
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/common/util.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/geoserver_test.py
- src/layman/layer/util.py
- src/layman/map/util.py
- src/layman/rest_multipublication_test.py
- src/layman_settings.py
- test/prime_db_schema_client.py
- test/process_client.py
Part of issue #159, #170 
Optionally
> Explicit bbox geoserver

- src/layman/layer/geoserver/geoserver_test.py
> Use directly celery tasks in test, instead of copying them

- src/layman/layer/qgis/util.py
> Fix QGIS file extent

- src/layman/geoserver_proxy_test.py
- test/data/wfs.py
>  Test also WFS-T Delete in test_wfs_bbox

- .github/workflows/main.yml
> Add Geoserver logs to artifacts in GitHub after tests

- src/geoserver/util.py
- src/layman/authn/oauth2_test.py
- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/__init__.py
- src/layman/layer/client_test.py
- src/layman/layer/geoserver/geoserver_test.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/qgis/wms_tasks.py
- src/layman/layer/rest_workspace_layer_style.py
- src/layman/layer/rest_workspace_layers_test.py
- test/process.py
- test/util.py
> Patch after wfst geoserver

- src/layman/celery.py
- src/layman/common/redis.py
- src/layman/geoserver_proxy.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/layer/rest_workspace_test.py
- src/layman/layer/util.py
- src/layman/make_celery.py
- src/layman/map/rest_workspace_map.py
- src/layman/map/rest_workspace_maps.py
- src/layman/map/rest_workspace_test.py
- src/layman/map/util.py
- src/layman/util.py
- src/layman/uuid.py
- test/flask_client.py
> Wfst in celery

- src/layman/authz/__init__.py
- src/layman/celery.py
- src/layman/common/__init__.py
- src/layman/common/redis.py
- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/micka/csw.py
- src/layman/layer/micka/tasks.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/layer/util.py
- src/layman/map/micka/csw.py
- src/layman/map/micka/tasks.py
- src/layman/map/rest_workspace_maps.py
- src/layman/uuid.py
> Wfst in celery II

- src/layman/celery.py
- src/layman/common/redis.py
- src/layman/geoserver_proxy.py
- src/layman/layer/empty_bbox_test.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/util.py
- src/layman/map/util.py
- src/layman/requests_concurrency_test.py
- src/layman/util.py
> Wfst concurrency

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/util.py
- src/layman/map/util.py
- src/layman/rest_publication_test.py
- src/layman/rest_responses_test.py
- src/layman/util.py
- test/process_client.py
> Layman metedata in get info

- CHANGELOG.md
- doc/async-tasks.md
- doc/endpoints.md
- doc/rest.md
> Improve documentation of asynchronous tasks and concurrency of requests

- src/layman/geoserver_proxy_test.py
- src/layman/layer/empty_bbox_test.py
- src/layman/requests_concurrency_test.py
- test/process_client.py
> Process client wfst

- CHANGELOG.md
- doc/dependencies.md
- docker/Dockerfile.dev
- docker/Dockerfile.production
> Upgrade pipenv

- CHANGELOG.md
- README.md
- client/docker/Dockerfile.production
- doc/dependencies.md
- doc/env-settings.md
- doc/oauth2/index.md
- src/layman/layer/rest_workspace_test.py
- src/layman/upgrade/upgrade_v1_10.py
- timgen/index.js
> Change Layman GitHub page

- .github/workflows/code_quality.yml
- .github/workflows/main.yml
> Run CI also for pull_request events

- src/layman/map/schema.draft-07.json
Add 'externalWFS' as a vector protocol format option
Add workspace layer property
> Composition schema additions

- src/layman/map/schema.draft-07.json
> feat: Use SLD to describe composition layers style

- CHANGELOG.md
- doc/dependencies.md
- docker/requirements.production.txt
Part of issue #347, #367
- ~~Tests~~
Optionally
> Fix changelog for Postgres upgrade

- .github/workflows/irritating.yml
- CHANGELOG.md
- doc/data-storage.md
- doc/rest.md
- src/layman/common/filesystem/util.py
- src/layman/error_list.py
- src/layman/layer/__init__.py
- src/layman/layer/filesystem/__init__.py
- src/layman/layer/filesystem/gdal.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/tasks.py
- src/layman/layer/filesystem/util.py
- src/layman/layer/rest_workspace_layers_test.py
- src/layman/layer/util.py
- src/layman_settings.py
> Introduce GDAL source

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/filesystem/gdal.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/layer/rest_workspace_layers_test.py
> Raster bbox

- CHANGELOG.md
- src/layman/celery.py
Part of issue #405
- ~~Tests~~
Optionally
> Fix #405 (forever PENDING publications).

- src/layman/layer/micka/csw.py
> Calculate scale_denominator and languages only for vector layers

- CHANGELOG.md
- doc/endpoints.md
- src/layman/geoserver_proxy.py
> Run patch_after_feature_change only for vector layers

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
> Upgrade LTC to version 1.9.0

- .github/workflows/irritating.yml
- CHANGELOG.md
- doc/rest.md
- test_separated.sh
> Fix GET Workspace Layer documentation, style -> sld

- src/layman/layer/geoserver/wfs.py
> Take out WFS metadata source for raster layers

- src/geoserver/util.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- tests/static_publications/__init__.py
- tests/static_publications/single_publication/publications_test.py
> Raster patch rights

- CHANGELOG.md
- sample/data/geometry-types/none_geometry.geojson
- src/layman/layer/qgis/util.py
- src/layman/layer/qgis/util_test.py
Part of issue #418, closing #418 
Optionally
> Allow combination of none geometry type in layer and all qml geometries

- src/layman/layer/db/tasks.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/prime_db_schema/tasks.py
> Not implemented publication type

- CHANGELOG.md
- Makefile
- README.md
Part of issue #383
- ~~Tests~~
Optionally
> Add new Makefile target to finish upgrade in case of GeoServer call timeout

- CHANGELOG.md
- README.md
- doc/about.md
- doc/async-file-upload.md
- doc/cs/o-aplikaci.md
- doc/data-storage.md
- doc/metadata.md
- doc/models.md
- doc/rest.md
> Finish documentation of rasters

- doc/dependencies.md
- docker/Dockerfile.dev
- docker/Dockerfile.production
> Improve chromium installation in dockerfile

- CHANGELOG.md
- src/layman/layer/util.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_14.py
- src/layman/upgrade/upgrade_v1_14_test.py
Part of issue #367 
Optionally
> Bounding boxes crop migration

- src/layman/layer/filesystem/input_file.py
- src/layman/layer/rest_workspace_layers.py
- test_tools/process_client.py
- test_tools/util.py
- tests/conftest.py
- tests/failed_publications/layers_test.py
- tests/static_publications/conftest.py
Part of issue #167, #387
Optionally
> Fix png pgw without crs

- tests/failed_publications/__init__.py
- tests/failed_publications/layers_test.py
> Test raster with qml error

- src/layman/common/filesystem/util.py
- src/layman/common/prime_db_schema/migrate_test.py
> Replace user/username with workspace

- CHANGELOG.md
- src/layman/celery.py
- src/layman/layer/util.py
- src/layman/layer/util_test.py
- src/layman/map/__init__.py
- src/layman/map/util.py
- src/layman/util.py
Part of issue #459 
Optionally
> Fix pending publications

- src/layman/authn/http_header/__init__.py
- src/layman/celery_test.py
- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/rest_workspace_test.py
- src/layman/map/client_test.py
- src/layman/map/filesystem/input_file.py
- src/layman/map/filesystem/tasks.py
- src/layman/map/filesystem/thumbnail.py
- src/layman/map/filesystem/util.py
- src/layman/map/filesystem/uuid.py
- src/layman/map/micka/csw.py
- src/layman/map/micka/csw_test.py
- src/layman/map/micka/soap.py
- src/layman/map/micka/tasks.py
- src/layman/map/prime_db_schema/tasks.py
- src/layman/map/rest_maps.py
- src/layman/map/rest_workspace_map.py
- src/layman/map/rest_workspace_map_file.py
- src/layman/map/rest_workspace_map_metadata_comparison.py
- src/layman/map/rest_workspace_map_thumbnail.py
- src/layman/map/rest_workspace_maps.py
- src/layman/map/rest_workspace_maps_test.py
- src/layman/map/rest_workspace_test.py
- src/layman/map/util.py
- src/layman/util.py
- src/layman/uuid.py
Part of issue #194 
Optionally
> Rename username in rest of layman

- CHANGELOG.md
- sample/layman.layer/strange_attribute_names.geojson
- sample/style/strange_attribute_names.qml
- src/layman/common/db/__init__.py
- src/layman/common/db/db_test.py
- src/layman/layer/db/__init__.py
- src/layman/layer/qgis/output_srs.py
- tests/static_publications/__init__.py
- tests/static_publications/single_publication/layers_test.py
Part of issue #459, #465, #464
Optionally
> Merge 1.14.1

- CHANGELOG.md
- doc/rest.md
- src/layman/__init__.py
- src/layman/layer/filesystem/input_style.py
- src/layman/layer/filesystem/input_style_test.py
- src/layman/tools/rest_tools.py
- src/layman/tools/rest_tools_test.py
- test_tools/data/style/circle.svg
- test_tools/data/style/small_layer_external_circle.qml
- test_tools/process_client.py
> Get files from style

- doc/rest.md
> Minor doc fixes

- doc/rest.md
- src/layman/error_list.py
- src/layman/layer/filesystem/input_style.py
- src/layman/layer/filesystem/input_style_test.py
- src/layman/layer/rest_workspace_layers.py
> External images checks

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/rest_workspace_layer.py
- test_tools/process_client.py
- tests/static_data/__init__.py
> More style files patch

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/__init__.py
- src/layman/layer/filesystem/input_style.py
- src/layman/layer/rest_workspace_layer_style_external_image.py
- test_tools/process_client.py
- tests/static_data/__init__.py
- tests/static_data/single_publication/layers_test.py
Part of issue #258 
Optionally
> Layer style external image

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/filesystem/input_style.py
- src/layman/layer/filesystem/input_style_test.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/tools/rest_tools.py
- tests/immutable_endpoints/rest_tools_test.py
Part of issue #258 
Optionally
> Get all external dependencies from qml

- src/layman/layer/db/tasks.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/tasks.py
- src/layman/layer/filesystem/util.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- tests/dynamic_data/publications.py
> Some tests related to ZIP files

- CHANGELOG.md
- doc/data-storage.md
- doc/rest.md
- src/layman/layer/filesystem/gdal.py
- src/layman/layer/filesystem/tasks.py
Part of issue #503
- ~~Tests~~
Optionally
> Compress normalized raster files

- src/layman/layer/filesystem/tasks.py
- tests/dynamic_data/publications/wrong_input.py
> 169 raster with qml

- tests/dynamic_data/publications/file_input.py
- tests/dynamic_data/publications/util.py
- tests/dynamic_data/publications/wrong_input.py
> Add patch part to file_input test

- src/geoserver/util.py
- src/layman/__init__.py
- src/layman/common/micka/__init__.py
- src/layman/common/micka/requests.py
- src/layman/common/micka/util.py
- src/layman/error_handlers.py
- src/layman/error_list.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/util.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/micka/csw.py
- src/layman/map/micka/csw.py
Part of issue #489 
- ~~Tests~~
Optionally
> Micka geoserver error logging

- CHANGELOG.md
- doc/rest.md
- src/db/util.py
- src/layman/common/bbox.py
- src/layman/common/prime_db_schema/migrate_test.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/rest.py
- src/layman/layer/__init__.py
- src/layman/layer/db/__init__.py
- src/layman/layer/filesystem/gdal.py
- src/layman/layer/micka/csw.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/layer/util_test.py
- src/layman/map/micka/csw.py
- src/layman/map/prime_db_schema/tasks.py
- src/layman/map/util.py
- src/layman/rest_responses_test.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_16.py
- test_tools/assert_util.py
- test_tools/data/map.py
- tests/dynamic_data/publications/__init__.py
- tests/dynamic_data/publications/file_input.py
> 64 get workspace layers

- src/geoserver/epsg_properties.py
- src/geoserver/geoserver_test.py
- src/geoserver/util.py
- src/layman/common/output_srs_list_test.py
- src/layman/layer/micka/csw.py
- src/layman/layer/qgis/util.py
- src/layman_settings.py
- test_tools/assert_util.py
- tests/static_data/single_publication/layers_test.py
> 64 layman output srs list strings

- src/db/util.py
- src/layman/layer/prime_db_schema/bbox.py
- src/layman/map/prime_db_schema/bbox.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/wrong_input.py
> 64 reset bbox crs on patch

- .github/workflows/irritating.yml
- .github/workflows/main.yml
- .github/workflows/separated_tests.yml
> Make test workflows do not run after *.md or *.txt changes

- src/layman/map/micka/csw.py
- src/layman/map/util.py
> Remove map_json_to_epsg_codes

- src/layman/celery.py
- test_tools/util.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publication_test.py
- tests/dynamic_data/publications/__init__.py
- tests/dynamic_data/publications/celery.py
> Improve waiting for task end

- deps/geoserver/sample/geoserver_data/wms.xml
- src/layman/celery.py
- src/layman/geoserver_proxy_test.py
- test_tools/assert_util.py
> Unskip tests in geoserver_proxy_test.py

- tests/dynamic_data/publications/geoserver_proxy.py
- tests/dynamic_data/publications/wrong_input.py
> Dynamic data tests improvements

- CHANGELOG.md
- doc/dependencies.md
- docker/Dockerfile.dev
- docker/Dockerfile.production
- docker/Pipfile
- docker/Pipfile.lock
- src/layman/__init__.py
- src/layman/layer/client_test.py
- src/layman/map/client_test.py
- src/layman/map/filesystem/thumbnail.py
- src/layman/util.py
- timgen/index.js
Part of issue #555
- ~~Tests~~
> Use Firefox instead of Chrome in Selenium

- .github/workflows/main.yml
- .github/workflows/separated_tests.yml
- CHANGELOG.md
- src/geoserver/util.py
- src/layman/celery.py
- src/layman/common/micka/requests.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/map/filesystem/thumbnail.py
- src/requests_util/retry.py
- tests/static_data/data.py
> Publish test static data in parallel 2

- .github/workflows/separated_tests.yml
> Change owner of layman_data_test in Github Actions

- src/crs/__init__.py
- src/db/util.py
- src/layman/__init__.py
- src/layman/common/bbox.py
- src/layman/common/output_srs_list_test.py
- src/layman/layer/db/table.py
- src/layman/layer/db/tasks.py
> 64 use special srid for 5514

- src/layman/common/bbox.py
- tests/asserts/final/publication/geoserver.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/crs/vectors/__init__.py
> 64 test bboxes

- CHANGELOG.md
- doc/endpoints.md
- src/layman/geoserver_proxy.py
- src/layman/layer/geoserver/wms.py
- tests/asserts/final/publication/geoserver.py
> Automatically add buffer to some special WMS GetMap requests

- test_tools/util.py
- test_tools/util_test.py
- tests/dynamic_data/publications/common_layers.py
- tests/dynamic_data/publications/crs/__init__.py
- tests/dynamic_data/publications/crs/vectors/__init__.py
- tests/dynamic_data/publications/file_input.py
- tests/dynamic_data/publications/util.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Internal tc parametrization reduction

- tests/dynamic_data/publications/crs/vectors/__init__.py
> In dynamic_data/crs/vectors run only POST for EPSG:3857 and EPSG:4326

- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/crs/vectors/__init__.py
> DB transformation precision

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/map_1_1_0_3030.json
- src/layman/upgrade/map_1_1_0_3857.json
- src/layman/upgrade/map_1_1_0_4326.json
- src/layman/upgrade/upgrade_v1_16.py
- src/layman/upgrade/upgrade_v1_16_test.py
> 64 map migration

- src/crs/__init__.py
- src/layman/common/bbox.py
- src/layman/common/bbox_test.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/geoserver_test.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/micka/csw.py
- src/layman/layer/qgis/wms.py
- src/layman/map/micka/csw.py
- tests/static_data/single_publication/layers_test.py
> Split crs.world_bbox to default_bbox and max_bbox

- CHANGELOG.md
- src/layman/celery.py
- src/layman/common/redis.py
- src/layman/map/filesystem/thumbnail.py
- src/layman/map/filesystem/thumbnail_tasks.py
- src/layman/requests_concurrency_test.py
> Patch run after chain

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- doc/dependencies.md
- doc/env-settings.md
- src/layman/make_celery.py
> Merge 1.16.2

- src/layman/common/micka/util.py
- ~Tests~
- ~Layman Test Client~
- ~Changlelog~
- ~Documentation~
Optionally
> Add logging for micka response

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/tasks.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman_settings.py
- test_tools/process_client.py
- tests/asserts/final/publication/util.py
- tests/dynamic_data/publications/layer_overview_resampling_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> 551 overview resampling

- CHANGELOG.md
- src/crs/__init__.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
> 606 fix bbox filter

- CHANGELOG.md
- doc/data-storage.md
- doc/models.md
- src/geoserver/util.py
- src/layman/error_list.py
- src/layman/geoserver_proxy.py
- src/layman/layer/db/__init__.py
- src/layman/layer/db/db_test.py
- src/layman/layer/db/table.py
- src/layman/layer/db/tasks.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/micka/csw.py
- src/layman/layer/prime_db_schema/bbox_tasks.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/layer/qgis/util.py
- src/layman/layer/qgis/util_test.py
- src/layman/layer/qgis/wms.py
- src/layman/layer/rest_workspace_test.py
- src/layman/rest_responses_test.py
- tests/asserts/final/publication/internal.py
- tests/static_data/single_publication/layers_test.py
> 541 encapsulate table name

- CHANGELOG.md
- doc/rest.md
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/layer/db/db_test.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/rest_multipublication_test.py
- src/layman/rest_responses_test.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_14_test.py
- src/layman/upgrade/upgrade_v1_17.py
- src/layman/upgrade/upgrade_v1_17_test.py
- test_tools/prime_db_schema_client.py
- tests/asserts/final/publication/internal.py
- tests/asserts/final/publication/rest.py
- tests/static_data/single_publication/publications_test.py
> Fill file_type in prime DB schema and use it

- tests/dynamic_data/base_test.py
- tests/dynamic_data/publications/crs/maps/maps_test.py
- tests/dynamic_data/publications/layer_overview_resampling/resampling_test.py
- tests/dynamic_data/publications/publication_name_test.py
> 541 merge pytest generate tests

- CHANGELOG.md
- doc/rest.md
- src/layman/common/rest.py
- src/layman/geoserver_proxy.py
- src/layman/layer/__init__.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/micka/csw.py
- src/layman/map/__init__.py
- src/layman/rest_responses_test.py
- src/layman/upgrade/upgrade_v1_17_test.py
- tests/asserts/final/publication/rest.py
> Change file_type to file.file_type in multi endpoints

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_17.py
- src/layman/upgrade/upgrade_v1_17_test.py
Part of issue #541 
Optionally
> Migrate table names to `layer_<uuid>` format

- src/layman/upgrade/upgrade_v1_17.py
Part of issue #541
- ~~Tests~~
Optionally
> Migrate only existing tables and feature types

- tests/dynamic_data/publications/publication_name_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Mark some tests as optional

- CHANGELOG.md
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
> 606 fix ordering bbox

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/rest_workspace_layers.py
- test_tools/process_client.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> 635 new regexp param

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/rest_workspace_layer.py
- test_tools/process_client.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
Part of issue #635 
Optionally
> Add time_regex param to PATCH Workspace Layer

- .remarkrc
- CHANGELOG.md
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/map/prime_db_schema/table.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_17_test.py
- src/layman/upgrade/upgrade_v1_18.py
- src/layman/upgrade/upgrade_v1_18_test.py
- test_tools/prime_db_schema_client.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
> Add column image_mosaic to publications table

- CHANGELOG.md
- src/layman/layer/filesystem/input_chunk.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/tasks.py
- src/layman/layer/rest_workspace_layers.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
> 635 store more files

- CHANGELOG.md
- src/layman/layer/db/tasks.py
- src/layman/layer/filesystem/gdal.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/tasks.py
- src/layman/layer/filesystem/util.py
- src/layman/layer/geoserver/tasks.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
- tests/static_data/single_publication/layers_files_test.py
> 635 normalize all files

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/rest_responses_test.py
- src/layman/upgrade/upgrade_v1_17_test.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/__init__.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
> Enable PATCH for timeseries layers

- doc/rest.md
- src/layman/layer/filesystem/util.py
- test_tools/process_client.py
- tests/__init__.py
- tests/dynamic_data/base_test.py
- tests/dynamic_data/publications/crs/maps/maps_test.py
- tests/dynamic_data/publications/implicit_name_test.py
- tests/dynamic_data/publications/layer_overview_resampling/resampling_test.py
- tests/dynamic_data/publications/layer_raster_contrast/contrast_test.py
- tests/dynamic_data/publications/publication_name_test.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
- tests/dynamic_data/publications/updating_layer_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Implicit layer names

- CHANGELOG.md
- doc/metadata.md
- src/layman/common/metadata.py
- src/layman/common/micka/__init__.py
- src/layman/common/micka/util.py
- src/layman/layer/__init__.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/micka/csw.py
- src/layman/layer/micka/record-template-filled.xml
- src/layman/layer/micka/record-template.xml
- src/layman/layer/micka/util_test.py
- src/layman/layer/micka/util_test_filled_template.xml
- src/layman/layer/rest_workspace_test.py
- src/layman/layer/util.py
- test_tools/data/micka/rest_test_filled_raster_template.xml
- test_tools/data/micka/rest_test_filled_template.xml
- tests/asserts/final/publication/__init__.py
- tests/asserts/final/publication/metadata.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
> 635 Add temporal_extent to metadata

- tests/dynamic_data/publications/geoserver_issues/raster_float_grayscale_alpha_contrast_enhancement.sld
- tests/dynamic_data/publications/geoserver_issues/wms_test.py
> Add test with GeoServer rendering issue #681.

- src/layman/layer/filesystem/gdal.py
- src/layman/layer/filesystem/gdal_test.py
- tests/dynamic_data/publications/layer_raster_contrast/contrast_test.py
> Calculate statistics from all main files

- doc/rest.md
- src/layman/layer/rest_workspace_layer.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> PATCH Workspace Layer supports time_regex only with files

- src/layman/layer/db/tasks.py
- src/layman/layer/filesystem/gdal.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/tasks.py
- src/layman/layer/filesystem/util.py
- src/layman/layer/geoserver/tasks.py
- src/layman/upgrade/upgrade_v1_17_test.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/__init__.py
> Revise file keys

- doc/rest.md
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/filesystem/tasks.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> All main datafiles have to match time_regex if time_regex is set

- src/layman/layer/filesystem/input_file.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Improve error message for more main files

- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
> 635 correct_values_in_detail parameters

- tests/dynamic_data/publications/wrong_input/__init__.py
> Fix wrong input tests

- tests/dynamic_data/publications/implicit_name_test.py
- tests/dynamic_data/publications/layer_raster_contrast/contrast_test.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Make some test optional

- src/layman/layer/geoserver/wms.py
- tests/dynamic_data/publications/timeseries/timeseries_test.py
> Fix PATCH timeseries layer

- src/layman/layer/geoserver/sld.py
- src/layman/layer/geoserver/sld_customized_raster_template.sld
Part of issue #446
- ~~Tests~~
> Add labels to customized SLD styles

- .remarkrc
> Remove https://openid.net/specs/openid-connect-core-1_0.html from .remarkrc

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- README.md
> Upgrade LTC to v1.13.0

- .github/workflows/optional_tests.yml
- Makefile
- test_separated.sh
- test_static.sh
- tests/dynamic_data/base_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Add GitHub workflow for optional tests

- .github/workflows/optional_tests.yml
- Makefile
- test_separated.sh
> Let test all optional tests

- CHANGELOG.md
- Makefile
- README.md
- deps/geoserver/docker/Dockerfile
- docker-compose.deps.demo.yml
- docker-compose.deps.yml
Part of issue #348 
- ~~Tests~~
Optionally
> 348 simplify gs docker

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- README.md
- client/docker/Dockerfile.production
- doc/dependencies.md
- src/layman/layer/client_test.py
- src/layman/map/client_test.py
Part of issue #726 
- ~~Tests~~
> Use current LTC with Node.js v18

- CHANGELOG.md
- doc/endpoints.md
- doc/rest.md
- src/layman/layer/rest_workspace_test.py
- tests/dynamic_data/publications/layer_style/layer_style_test.py
> Test GET Workspace Layer Style

- src/layman/util.py
Part of issue #720 
Optionally
> Fix info keys after celery upgrade

- src/geoserver/util.py
Part of issue #348
- ~~Tests~~
Optionally
> 348 GS ensure workspace conflict

- src/geoserver/util.py
- src/layman/layer/geoserver/sld.py
- tests/dynamic_data/publications/issues/gs_sld_style_test.py
- tests/dynamic_data/publications/layer_style/layer_style_test.py
Part of issue #348, #738
Optionally
> 348  Return SLD style in version it was sent

- doc/rest.md
- src/db/__init__.py
- src/db/util.py
- src/layman/layer/util.py
- src/layman/layer/util_test.py
- test_tools/external_db.py
- tests/__init__.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> 703 Validate db_connection parameter

- docker-compose.test.yml
- src/clear_layman_data.py
- src/conftest.py
- src/layman/layer/util_test.py
- test_tools/external_db.py
- tests/conftest.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
> Use fixture for external test DB, crop it before tests

- test_tools/external_db.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
> Test geometry types in external DB

- CHANGELOG.md
- src/db/__init__.py
- src/db/util.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/layer/util.py
- src/layman/layer/util_test.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_20.py
- src/layman/upgrade/upgrade_v1_20_test.py
- test_tools/external_db.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Rename internal methods (variables, ...) related to external DB

- doc/rest.md
- src/layman/layer/util.py
- src/layman/layer/util_test.py
- test_tools/external_db.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
> Test unusual names, split table and schema in db_connection

- src/layman/layer/util_test.py
> Test also parse URI params in db_connection

- src/layman/layer/util.py
- src/layman/layer/util_test.py
> If table/schema differs in letter case only, suggest it to the user

- CHANGELOG.md
- README.md
- doc/dependencies.md
- timgen/Dockerfile.production
Part of issue #755
- ~~Tests~~
Optionally
> Downgrade Node.js for Timgen to v16

- src/geoserver/util.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/util.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
> 703 Delete

- CHANGELOG.md
- src/layman/layer/rest_workspace_layer_style.py
- src/layman/layer/rest_workspace_layer_thumbnail.py
- src/layman/map/rest_workspace_map_file.py
- src/layman/map/rest_workspace_map_thumbnail.py
Part of issue #772
- ~~Tests~~
Optionally
> Speed up GET Layer/Map Style/Thumbnail/File endpoints

- tests/dynamic_data/publications/layer_external_db/external_db_test.py
> Reduce external_db_test.py

- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/db/__init__.py
- src/layman/layer/db/db_test.py
- src/layman/layer/db/table.py
- src/layman/layer/db/tasks.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/prime_db_schema/file_data_tasks.py
- src/layman/layer/qgis/util_test.py
- test_tools/cleanup.py
- test_tools/external_db.py
- tests/dynamic_data/base_test.py
- tests/dynamic_data/base_test_classes.py
- tests/dynamic_data/base_test_util.py
- tests/dynamic_data/base_test_util_test.py
- tests/dynamic_data/publications/wfst/refresh_test.py
- tests/static_data/single_publication/layers_test.py
> Refresh bbox and thumbnail after WFS-T on external DB table

- test_tools/external_db.py
- tests/dynamic_data/base_test.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/layer_external_db/patch_after_external_db_test.py
- tests/dynamic_data/publications/wfst/refresh_test.py
> Add import_external_table to base test class

- doc/rest.md
- src/layman/layer/util.py
- src/layman/layer/util_test.py
- test_tools/external_db.py
- tests/asserts/final/publication/geoserver.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/layer_external_db/patch_after_external_db_test.py
> Determine external table geo column if not specified

- src/layman/common/prime_db_schema/publications.py
- src/layman/upgrade/upgrade_v1_20.py
> Encrypt external_table_uri column in publications table

- doc/rest.md
- src/layman/layer/rest_workspace_layers.py
- tests/dynamic_data/publications/implicit_name_test.py
> 703 Derivation of implicit layer name from table name

- src/layman/geoserver_proxy_test.py
- src/layman/layer/rest_workspace_layers.py
- test_tools/external_db.py
- test_tools/process.py
- tests/dynamic_data/base_test.py
- tests/dynamic_data/base_test_util.py
- tests/dynamic_data/base_test_util_test.py
- tests/dynamic_data/publications/wfst/new_attribute_test.py
- tests/dynamic_data/publications/wfst/refresh_test.py
> Test WFS-T new attribute also for external table

- CHANGELOG.md
- doc/rest.md
- src/layman/common/prime_db_schema/publications.py
- src/layman/layer/__init__.py
- src/layman/layer/db/__init__.py
- src/layman/layer/db/tasks.py
- src/layman/layer/filesystem/tasks.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/prime_db_schema/file_data.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/layer/util.py
- src/layman/map/prime_db_schema/table.py
- src/layman/rest_responses_test.py
- src/layman_settings.py
- tests/asserts/final/publication/internal.py
- tests/static_data/single_publication/layers_test.py
> 703 original data source

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/layer/util.py
- src/layman/layer/util_test.py
- src/layman/upgrade/upgrade_v1_20.py
- src/layman/upgrade/upgrade_v1_20_test.py
- test_tools/process_client.py
- tests/dynamic_data/base_test_util_test.py
- tests/dynamic_data/publications/implicit_name_test.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/layer_external_db/patch_after_external_db_test.py
- tests/dynamic_data/publications/layer_wfst/new_attribute_test.py
- tests/dynamic_data/publications/layer_wfst/refresh_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
- tests/dynamic_data/publications/wrong_input/wfst.py
Part of issue #703 
- ~~Tests~~
> Rename db_connection to external_table_uri

- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layer_metadata_comparison.py
- src/layman/layer/util.py
- src/layman/map/rest_workspace_map.py
- src/layman/map/rest_workspace_map_metadata_comparison.py
- src/layman/map/util.py
> Remove info decorators

- src/layman/geoserver_proxy_test.py
- src/layman/layer/db/__init__.py
- src/layman/layer/db/db_test.py
- src/layman/layer/db/table.py
- src/layman/layer/db/tasks.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/upgrade/upgrade_v1_17_test.py
- tests/static_data/single_publication/layers_test.py
> Revise layman.layer.db method names

- src/layman/layer/__init__.py
- src/layman/layer/db/table.py
- test_tools/external_db.py
- tests/dynamic_data/publications/layer_unavailable_source/unavailable_db_table_test.py
> Test layer detail if table is not available

- src/crs/__init__.py
- src/db/util.py
- src/layman/__init__.py
- src/layman/common/bbox.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/layer/db/__init__.py
- src/layman/layer/db/tasks.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/layer/qgis/util.py
- src/layman/layer/util.py
- src/layman/upgrade/upgrade_v1_16.py
- src/layman/upgrade/upgrade_v1_17_test.py
- tests/asserts/final/publication/internal.py
- tests/static_data/single_publication/layers_test.py
> Rename CRSTypeDef.srid, revise names of some DB methods

- README.md
- doc/about.md
- doc/cs/o-aplikaci.md
- doc/data-storage.md
- doc/models.md
- doc/rest.md
> 703 Finalize documentation

- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/layer_external_db/patch_after_external_db_test.py
- tests/dynamic_data/publications/layer_unavailable_source/unavailable_db_table_test.py
- tests/dynamic_data/publications/layer_wfst/new_attribute_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
- tests/dynamic_data/publications/wrong_input/wfst.py
> 703 reduce tests

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
> Use Layman Test Client v1.15.0

- CHANGELOG.md
- docker/Pipfile.lock
> Upgrade OWSLib

- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/crs/__init__.py
- tests/dynamic_data/publications/crs/maps/maps_test.py
- tests/dynamic_data/publications/crs/rasters/__init__.py
- tests/dynamic_data/publications/crs/vectors/__init__.py
> Set thumbnail_equals max_diffs default to 5

- CHANGELOG.md
- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- test_tools/data/wfs.py
- tests/dynamic_data/publications/layer_wfst/new_attribute_test.py
> 812 implicit wfst namespace

- src/layman/common/prime_db_schema/publications.py
- src/layman/layer/__init__.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/map/prime_db_schema/table.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_21.py
- src/layman/upgrade/upgrade_v1_21_test.py
- src/layman_settings.py
- tests/asserts/final/publication/__init__.py
- tests/asserts/final/publication/internal.py
> Add wfs_wms_status internal info with hardcoded value

- CHANGELOG.md
- doc/rest.md
- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/filesystem/input_file_test.py
- src/layman/layer/qgis/wms.py
- test_tools/data/wfs.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/layer_wfst/new_attribute_test.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Merge 1.20.1

- CHANGELOG.md
- doc/rest.md
- src/layman/common/rest.py
- src/layman/map/__init__.py
- src/layman/rest_responses_test.py
- tests/asserts/final/publication/__init__.py
- tests/asserts/final/publication/internal_rest.py
- tests/static_data/single_publication/publications_test.py
> Add `wfs_wms_status` to GET (Workspace) Layers endpoints response

- CHANGELOG.md
- src/layman/map/filesystem/thumbnail.py
- tests/dynamic_data/publications/edge_cases/__init__.py
- timgen/src/map.js
Part of issue #833
- ~~Tests~~
Optionally
> Timgen handles XML errors better

- src/layman/celery.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/layer/__init__.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/layer/prime_db_schema/wfs_wms_status.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/util.py
- tests/dynamic_data/publications/updating_layer_test.py
- tests/dynamic_data/publications/wrong_input/wrong_input_test.py
Part of issue #528 
Optionally
> 528 Add wfs_wms_status values PREPARING and NOT_AVAILABLE

- tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> Use RUN_ONLY_CASES in wrong_input_test

- test_tools/process.py
- tests/dynamic_data/base_test.py
- tests/dynamic_data/publications/layer_by_used_servers/layer_patch_without_data_test.py
> Test patch without data for layers by used servers

- tests/dynamic_data/publications/wrong_input/util.py
- tests/dynamic_data/publications/wrong_input/util_test.py
- tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> Enable dimensions in wrong input test cases

- src/layman_settings.py
> Make wfs_wms_status values uppercase

- CHANGELOG.md
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/layer/db/db_test.py
- src/layman/rest_multipublication_test.py
- src/layman/upgrade/upgrade_v1_21.py
- src/layman/upgrade/upgrade_v1_21_test.py
- test_tools/prime_db_schema_client.py
> Set wfs_wms_status for existing publications

- src/layman/__init__.py
- src/layman/layer/prime_db_schema/wfs_wms_status.py
- src/layman/layer/prime_db_schema/wfs_wms_status_test.py
> Set wfs_wms_status after Layman restart

- CHANGELOG.md
- docker-compose.deps.demo.yml
- docker-compose.deps.yml
Part of issue #815
- ~~Tests~~
> Set GEOSERVER_CSRF_WHITELIST in docker-compose for geoserver

- doc/rest.md
Part of issue #528 
- ~~Tests~~
> Document wfs_wms_status in detail

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- doc/env-settings.md
- src/geoserver/util.py
- src/layman/common/micka/util.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/micka/csw.py
- src/layman/layer/micka/csw_test.py
- src/layman/layer/micka/soap.py
- src/layman/layer/micka/util_test.py
- src/layman/map/micka/csw.py
- src/layman/map/micka/csw_test.py
- src/layman/map/micka/soap.py
- src/layman/upgrade/upgrade_v1_17_test.py
- src/layman_settings.py
- tests/asserts/final/publication/geoserver.py
- tests/asserts/final/publication/geoserver_proxy.py
- tests/asserts/final/publication/geoserver_util.py
- tests/static_data/single_publication/layers_test.py
> 520 Add MetadataURL to layer definition on GS

- CHANGELOG.md
- src/geoserver/util.py
- src/layman/upgrade/upgrade_v1_21.py
- src/layman/upgrade/upgrade_v1_21_test.py
> Add MetadataURL to existing layer definition on GS

- tests/asserts/final/publication/rest.py
- tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> Fix same_values_in_detail_and_multi for async wrong input tests

- src/layman/rest_multipublication_test.py
- src/layman/rest_responses_test.py
- src/layman/upgrade/upgrade_v1_17_test.py
- test_tools/process_client.py
- tests/asserts/final/publication/rest.py
- tests/dynamic_data/publications/multi_publications/test_multiendpoints.py
- tests/static_data/multi_publications/publications_test.py
- tests/static_data/single_publication/publications_test.py
> 769 multienpoins revision

- CHANGELOG.md
- docker/Pipfile.lock
- timgen/package-lock.json
- timgen/package.json
> Upgrade deps

- .github/workflows/dynamic_tests.yml
- .github/workflows/main.yml
- .github/workflows/optional_tests.yml
- .github/workflows/static_tests.yml
- CHANGELOG.md
- Makefile
- Makefile_docker-compose_v1
- README.md
- docker/Dockerfile.production
Part of issue #877
- ~~Tests~~
> Use docker compose v2

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
> Use LTC v1.16.0

- src/layman/layer/util.py
- src/layman/upgrade/upgrade_v1_21_test.py
> Fix set_wfs_wms_status_after_fail for raster layers

- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_21.py
Part of issue #520 
- ~~Tests~~
> Run MetadataURL migration on GeoServer

- tests/dynamic_data/publications/multi_publications/test_multiendpoints.py
> 769 test refactoring

- tests/dynamic_data/publications/layer_external_db/patch_after_external_db_test.py
> Remove redundant test

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- doc/env-settings.md
- src/layman/__init__.py
- src/layman_settings.py
Part of issue #893
- ~~Tests~~
> 893 - Enable to set LOGLEVEL by environment variable

- Makefile
Part of issue #880 
- ~~Tests~~
> All `make` commands uses Docker Compose v2

- tests/asserts/final/publication/__init__.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/base_test_classes.py
- tests/dynamic_data/publications/map_layer_relation/map_layer_relation.py
> 868 Assert consistency of map layers between map JSON and DB

- Makefile
- src/layman/common/prime_db_schema/publications.py
- src/layman/layer/__init__.py
- src/layman/map/prime_db_schema/table.py
- src/layman/publication_relation/util.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/map_layer_relation/map_layer_relation.py
- tests/static_data/multi_publications/publications_test.py
> 868 patch_after_wfst_change reads map-layer relation from DB

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- doc/client-proxy.md
- src/layman/util.py
- src/layman/util_test.py
Part of issue #868 
- ~~Tests~~
> Use LTC with X-Forwarded headers

- src/layman/layer/micka/csw.py
- tests/dynamic_data/publications/layer_by_used_servers/layer_by_used_servers_test.py
> Fix default value of temporal_extent metadata property

- CHANGELOG.md
- sample/layman.map/internal_url.json
- src/layman/map/util.py
- src/layman/upgrade/upgrade_v1_22.py
> Merge 1.22.1

- CHANGELOG.md
- src/layman/layer/rest_workspace_layer.py
- src/layman/map/filesystem/input_file.py
- src/layman/map/rest_workspace_map.py
- test_tools/process.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/wrong_input/util.py
- tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> 952 Do not save map file if access rights are wrong

- tests/dynamic_data/publications/access_rights/test_access_rights_application.py
> Add some additional role access rights application tests

- CHANGELOG.md
> Document that GET Workspace Map respects role access rights

- CHANGELOG.md
- src/layman/common/prime_db_schema/publications.py
- src/layman/util.py
- tests/dynamic_data/publications/access_rights/test_access_rights_application.py
> Multi-endpoints respect role access rights

- .github/workflows/code_quality.yml
- .github/workflows/dynamic_tests.yml
- .github/workflows/main.yml
- .github/workflows/optional_tests.yml
- .github/workflows/static_tests.yml
> Upgrade GitHub actions

- src/geoserver/role_service.py
- src/layman/__init__.py
- src/layman/authz/role_service.py
> 165 - Validations at Layman start

- src/layman/authz/role_service.py
> Fix JDBC role service check error message

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_23.py
> Migration - Delete technical roles from former GeoServer role service

- CHANGELOG.md
- doc/models.md
- doc/rest.md
- src/layman/authn/oauth2_test.py
- src/layman/common/prime_db_schema/__init__.py
- src/layman/error_list.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_23.py
- src/layman/upgrade/upgrade_v1_23_test.py
- test_tools/process.py
- test_tools/process_client.py
- tests/dynamic_data/publications/wrong_input/wrong_input_test.py
- tests/dynamic_data/users_roles/test_current_user.py
> 165 Restrict workspace and user name length

- tests/dynamic_data/publications/access_rights/test_access_rights_application.py
- tests/dynamic_data/publications/access_rights/test_role.py
- tests/dynamic_data/publications/multi_publications/test_delete_multiendpoints.py
> 165 Make most new tests optional

- src/layman/upgrade/upgrade_v1_23.py
> Fix user role in delete_user_roles data migration

- tests/dynamic_data/publications/map_layer_relation/internal_hranice.json
- tests/dynamic_data/publications/map_layer_relation/internal_wms_and_wfs.json
- tests/dynamic_data/publications/map_layer_relation/map_layer_relation_test.py
> Fix optional tests

- CHANGELOG.md
- doc/rest.md
- src/layman/authz/role_service.py
- tests/dynamic_data/users_roles/test_roles.py
> Order roles in GET Roles result

- CHANGELOG.md
- doc/rest.md
- docker-compose.demo.yml
- docker-compose.dev.yml
- src/layman/authz/role_service.py
- src/wait_for_layman.py
- tests/dynamic_data/users_roles/test_roles.py
Part of issue #165, #1016
- ~~Tests~~
Optionally
> Merge 1.23.1

- CHANGELOG.md
- docker-compose.deps.demo.yml
Part of issue #1021, #1022
- ~~Tests~~
> Add release 1.23.2 to master

- src/layman/upgrade/upgrade_v2_0.py
Part of issue #1009
- ~~Tests~~
> Fix description migration

- CHANGELOG.md
- src/layman/layer/micka/soap.py
- src/layman/layer/micka/soap_tasks.py
- src/layman/layer/micka/tasks.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_test.py
- src/layman/requests_concurrency_test.py
- test_tools/process_client.py
Part of issue #1009
On [pre-prod server](http://157.230.109.174/client/) was PATCH Layer of access rights speed up from 16s to 10.5s
> Patch micka layer records asynchronously

- .github/workflows/tests_dynamic.yml
- .github/workflows/tests_dynamic_optional.yml
- .github/workflows/tests_src.yml
- .github/workflows/tests_static.yml
- CHANGELOG.md
- README.md
- doc/rest.md
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/rest.py
- src/layman/layer/__init__.py
- src/layman/map/__init__.py
- src/layman/map/prime_db_schema/table.py
- src/layman/publication_relation/util.py
- src/layman/rest_responses_test.py
- tests/asserts/final/publication/internal.py
- tests/asserts/final/publication/rest.py
- tests/dynamic_data/publications/map_layer_relation/map_layer_relation_test.py
> Add key used_in_maps in get layer, get layers, get publications endoint

- Makefile
- README.md
- src/layman/common/bbox.py
- src/layman/common/bbox_test.py
- src/layman/layer/filesystem/thumbnail.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/qgis/wms.py
- tests/static_data/single_publication/layers_test.py
> Encapsulate get_functioning_bbox

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- doc/rest.md
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/map/rest_workspace_maps.py
- src/layman/util.py
- src/layman/uuid.py
- test_tools/process_client.py
- tests/dynamic_data/publications/uuid/publish_publication_test.py
- https://github.com/LayerManager/layman-test-client/pull/104
> 1048 UUID as input param

- .github/workflows/tests_dynamic_optional_uuid_branch.yml
> Run optional tests weekly also on 1048-UUID-master branch

- src/layman/layer/geoserver/tasks.py
- src/layman/util.py
> Create and use get_publication_info_by_uuid

- CHANGELOG.md
- doc/rest.md
- src/layman/__init__.py
- src/layman/authn/redis.py
- src/layman/common/filesystem/util.py
- src/layman/error_list.py
- src/layman/user/rest_user.py
- src/layman/user/util.py
- test_tools/process.py
- test_tools/process_client.py
- tests/dynamic_data/users_roles/delete_user_test.py
- [ x] Tests
- [ x] Changelog
- [ x] Documentation
> Consider DELETE Workspace/User endpoint

- .github/workflows/code_quality.yml
- Makefile
- docker-compose.test.yml
- migration_to_v2_0_tests/tests/migrated_data_test.py
- migration_to_v2_0_tests/tools/client.py
- migration_to_v2_0_tests/tools/oauth2_provider_mock.py
- migration_to_v2_0_tests/tools/test_data.py
> 1048 Check code quality in migration_to_v2_0_tests

- CHANGELOG.md
- Makefile
Part of issue #909 
- ~~Tests~~
> 909 Mention explicit build of QGIS in CHANGELOG.md

- CHANGELOG.md
- Makefile
Part of issue #909 
- ~~Tests~~
> 909 Upmerge: Mention explicit build of QGIS in CHANGELOG.md

- CHANGELOG.md
- src/layman/upgrade/upgrade_v2_0.py
> 1048 Improve geoserver migration

- src/layman/authz/__init__.py
- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/qgis/wms.py
- src/layman/publication_relation/layer_map_relation_test.py
- test_tools/assert_util.py
- test_tools/data/wfs.py
- test_tools/process_client.py
- tests/asserts/final/publication/geoserver.py
- tests/dynamic_data/base_test.py
- tests/dynamic_data/publications/access_rights/test_access_rights_application.py
- tests/dynamic_data/publications/crs/rasters/precision_test.py
- tests/dynamic_data/publications/geoserver_proxy.py
- tests/dynamic_data/publications/issues/gs_wfst_update_replace.py
- tests/dynamic_data/publications/layer_wfst/new_attribute_test.py
- tests/dynamic_data/publications/layer_wfst/refresh_test.py
- tests/dynamic_data/publications/map_layer_relation/patch_after_feature_change_map.json
- tests/dynamic_data/publications/map_layer_relation/patch_after_feature_change_test.py
- tests/dynamic_data/publications/wrong_input/wfst_test.py
> 1048 Fix geoserver_proxy for GS layers named by UUID

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
Part of issue #161
- ~~ Tests ~~
- ~~ Documentation ~~
Optionally
> 161 Update test client

- src/layman/layer/qgis/wms.py
- test_tools/process_client.py
- tests/dynamic_data/publications/geoserver_proxy.py
- tests/dynamic_data/publications/wrong_input/util.py
- tests/dynamic_data/publications/wrong_input/util_test.py
- tests/dynamic_data/publications/wrong_input/wrong_input_test.py
> 1048 Fix optional tests

- CHANGELOG.md
- migration_to_v2_0_tests/prepare_data_on_v1_23.py
- migration_to_v2_0_tests/tests/migrated_data_test.py
- migration_to_v2_0_tests/tools/test_data.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v2_0.py
- src/layman/upgrade/upgrade_v2_0_util.py
> 1048 Migrate filesystem providers

- CHANGELOG.md
- doc/data-storage.md
- doc/models.md
- src/layman/layer/db/__init__.py
- src/layman/layer/db/db_test.py
- src/layman/layer/db/table.py
- src/layman/layer/db/tasks.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/geoserver/util.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/layer_class.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/layer/qgis/util_test.py
- src/layman/layer/rest_workspace_test.py
- src/layman/rest_responses_test.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v2_0.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/access_rights/test_access_rights_application.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/layer_external_db/patch_after_external_db_test.py
- tests/dynamic_data/publications/layer_unavailable_source/unavailable_db_table_test.py
- tests/static_data/single_publication/layers_test.py
> 1048 Save DB table in global schema

- CHANGELOG.md
- migration_to_v2_0_tests/tests/migrated_data_test.py
- migration_to_v2_0_tests/tools/test_data.py
- src/layman/upgrade/upgrade_v2_0.py
> 1048 Migrate layer DB tables

- docker-compose.demo.yml
- src/layman/common/micka/util.py
- src/layman/layer/layer_class.py
- src/layman/layer/micka/csw.py
- src/layman/layer/micka/csw_test.py
- src/layman/layer/micka/soap.py
- src/layman/layer/micka/soap_tasks.py
- src/layman/layer/micka/tasks.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layer_metadata_comparison.py
- src/layman/layer/util.py
- src/layman/map/map_class.py
- src/layman/map/micka/csw.py
- src/layman/map/micka/csw_test.py
- src/layman/map/micka/soap.py
- src/layman/map/micka/tasks.py
- src/layman/map/rest_workspace_map.py
- src/layman/map/rest_workspace_map_metadata_comparison.py
- src/layman/map/rest_workspace_test.py
- src/layman/map/util.py
- src/layman/publication_class.py
- tests/asserts/final/publication/metadata.py
- tests/dynamic_data/publications/layer_by_used_servers/layer_by_used_servers_test.py
- tests/dynamic_data/publications/layer_timeseries/timeseries_test.py
- tests/dynamic_data/publications/map_layer_relation/map_layer_relation_test.py
- tests/static_data/single_publication/layers_test.py
> 1048 Use Layer/Map classes in Micka sources

- src/layman/upgrade/upgrade_v2_0.py
- src/layman/upgrade/upgrade_v2_0_util.py
> 1048 Only log warning if some data remains in migrated directory

- tests/dynamic_data/users_roles/delete_user_test.py
> 161 test delete user with publication shared with role

- CHANGELOG.md
- Makefile
- README.md
> 1048 Save upgrade demo logs

- CHANGELOG.md
- src/layman/common/output_srs_list_test.py
- src/layman/layer/layer_class.py
- src/layman/layer/qgis/layer-template.qml
- src/layman/layer/qgis/util.py
- src/layman/layer/qgis/wms.py
- tests/static_data/single_publication/layers_test.py
> Use title in Qgis layers legend

- src/layman/celery_test.py
- src/layman/geoserver_proxy.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/layer_class.py
- src/layman/layer/micka/csw.py
- src/layman/layer/util.py
- src/layman/map/map_class.py
- src/layman/map/micka/csw.py
- src/layman/map/util.py
- src/layman/publication_class.py
- src/layman/publication_relation/util.py
- src/layman/util.py
- tests/asserts/final/publication/metadata.py
- tests/dynamic_data/publications/map_layer_relation/map_more_internal_layers_referenced_by_workspace_name.json
> 1048 All get_metadata_comparison methods get Publication class as param

- tests/dynamic_data/users_roles/delete_user_test.py
> 161 add ids to indirect pytest parametrizations

- src/layman/layer/micka/csw.py
- src/layman/layer/micka/soap_tasks.py
> Remove unneeded backup_uuid argument

- src/layman/layer/micka/csw.py
- src/layman/layer/micka/soap_tasks.py
- test_dynamic.sh
- test_src.sh
- test_static.sh
> Revert unintentional changes in test_*.sh files

- CHANGELOG.md
- README.md
- doc/dependencies.md
- docker-compose.deps.demo.yml
- docker-compose.deps.yml
> Upgrade geoserver

- src/layman/layer/micka/csw.py
- src/layman/layer/micka/soap_tasks.py
(cherry picked from commit c56e6201bcef22dce2b8fddaed0d42345914c28c)
- ~~Tests~~
> 1048 Remove backup UUID

- CHANGELOG.md
- doc/data-storage.md
- doc/models.md
- doc/rest.md
- src/layman/upgrade/upgrade_v2_0.py
> 1048 Update changelog and documentation

- .github/workflows/tests_migration_to_v2.yml
- tests/README.md
> 1048 Run migration 2.0 test on PR to master branch

- .github/workflows/tests_dynamic_optional.yml
- src/layman/layer/filesystem/input_chunk.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/map/prime_db_schema/table.py
- tests/dynamic_data/publications/edge_cases/test_edge_cases.py
> Fix PATCH without access rights

- src/layman/layer/rest_workspace_layer_chunk.py
To have more info about failing tests on Github Actions related to chunks
- ~~Tests~~
> Log chunk size

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
> Upgrade Layman test client to v2.0.0

- src/layman/authz/__init__.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/map/prime_db_schema/table.py
- src/layman/util.py
> get_publication_infos enable filtering by publication name

- src/layman/layer/rest_workspace_test.py
- src/layman/map/micka/csw_test.py
- src/layman/map/rest_workspace_test.py
- test_tools/process_client.py
> Rewrite layer/map rest_workspace_test

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v3_0.py
- src/layman/upgrade/upgrade_v3_0_test.py
> Migrate graphic_url in map metadata to UUID-based format

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v3_0.py
- src/layman/upgrade/upgrade_v3_0_test.py
> Migrate graphic url in url metadata

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v3_0.py
- src/layman/upgrade/upgrade_v3_0_test.py
> Migrate map_file_endpoint in map metadata to UUID-based format

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
Part of issue #1126 
- ~~[ ] Tests~~
Optionally
> upgrade LTC version
