LayerManager/layman

- CHANGELOG.md
- src/layman/__init__.py
- src/layman/error_list.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/rest_test.py
- src/layman/util.py
I've faced an issue when existing username was the same as LAYMAN_GS_USER. Before v1.6.0 it was not a problem, but at v1.6.0 when we started to create users at GeoServer, both usernames are in conflict.
This PR comes with detection of such conflict in `check_username`, that is now called both on Layman startup and `reserve_username`. Error message contains hint how to solve this error, also mentioned in changelog.
> Detect LAYMAN_GS_USER username conflict

- .env.demo
- .env.dev
- .env.test
- src/layman/__init__.py
- src/layman/common/prime_db_schema/migrate_test.py
- src/layman/common/prime_db_schema/model.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/common/prime_db_schema/schema_initialization.py
- src/layman/common/prime_db_schema/users_test.py
- src/layman/common/prime_db_schema/util.py
- src/layman/common/prime_db_schema/workspaces_test.py
- src/layman/layer/prime_db_schema/table.py
- src/layman/layer/rest_layers_test.py
- src/layman/layer/rest_test.py
- src/layman/map/prime_db_schema/table.py
- src/layman/map/rest_maps_test.py
- src/layman/uuid.py
- test/flask_client.py
- test/process.py
- test/process_client.py
- test/util.py
Improvements in prime_db_publications:
- get_publication_infos return dictionary with tuple (workspace, pub_type, pub_name) as a key
- uuid is type uuid
- use workspace instead of username for variable names
Small improvements in prime_db_schema migration
Use Layman Test Client v1.3.0
> prime_db_schema.get_publication_infos return dictionary with tuple key

- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/error_list.py
- src/layman/gs_wfs_proxy_test.py
> Access rights are tested against axioms

- CHANGELOG.md
- doc/models.md
- doc/rest.md
> Add access_rights into documentation and changelog.

- src/layman/authz/authz_test.py
- test/process_client.py
> Rewrite envi.variable test for Public workspaces with parametrization and add test of maps to it

- CHANGELOG.md
- doc/async-file-upload.md
- doc/publish-map.md
- doc/rest.md
- src/layman/layer/geoserver/sld.py
- src/layman/layer/rest_layer.py
- src/layman/layer/rest_layer_test.py
- src/layman/layer/rest_layers.py
- src/layman/layer/rest_test.py
- src/layman/layer/util.py
- src/layman/upgrade/upgrade_v1_10_test.py
- test/process_client.py
> Use 'style' instead of deprecated 'sld' parameter

- CHANGELOG.md
- src/layman/layer/micka/csw.py
- src/layman/layer/rest_workspace_layers_test.py
> Add v1.10.1 to master

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- doc/rest.md
- src/layman/common/get_publications_consts.py
- src/layman/common/prime_db_schema/migrate_test.py
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/common/rest.py
- src/layman/common/util.py
- src/layman/layer/rest_layers.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/map/rest_maps.py
- src/layman/map/rest_workspace_maps.py
- src/layman/rest_multipublication_test.py
- src/layman/rest_publication_test.py
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_10.py
- src/layman/upgrade/upgrade_v1_12.py
- src/layman/upgrade/upgrade_v1_12_test.py
- src/layman/util_test.py
Part of issue #257 
Optionally
> Order by last change

- CHANGELOG.md
- doc/metadata.md
- src/layman/__init__.py
- src/layman/common/metadata.py
- src/layman/layer/micka/csw.py
- src/layman/layer/micka/util_test_filled_template.xml
- src/layman/layer/rest_test_filled_template.xml
> Add LAYERS URL parameter to wms_url/wfs_url metadata properties

- CHANGELOG.md
- doc/endpoints.md
- src/layman/common/tasks.py
- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/prime_db_schema/bbox_tasks.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/layer/util.py
- src/layman/make_celery.py
- test/data/wfs.py
> Patch after wfst prime schema

- src/geoserver/util.py
- src/layman/common/bbox.py
- src/layman/common/bbox_test.py
- src/layman/common/metadata.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/micka/csw.py
- src/layman/layer/micka/soap_tasks.py
- src/layman/layer/rest_test_filled_template.xml
- src/layman/map/micka/csw.py
- src/layman/map/rest_test_filled_template.xml
- test/util.py
> micka.soap: patch_after_wfst

- .github/workflows/irritating.yml
- CHANGELOG.md
- doc/rest.md
- docker-compose.test.yml
- src/layman/layer/__init__.py
- src/layman/layer/client_test.py
- src/layman/layer/filesystem/input_chunk.py
- src/layman/layer/filesystem/input_file.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layer_chunk_test.py
- src/layman/layer/rest_workspace_layer_test.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/layer/rest_workspace_layers_test.py
- src/layman/map/rest_workspace_test.py
- src/layman/rest_publication_test.py
- test.sh
- test/process_client.py
- test/util.py
> Raster with qml

- CHANGELOG.md
- doc/rest.md
- src/layman/layer/db/tasks.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/geoserver/wfs_tasks.py
- src/layman/layer/geoserver/wms_tasks.py
- src/layman/layer/micka/util_test.py
- src/layman/layer/prime_db_schema/bbox_tasks.py
- src/layman/layer/prime_db_schema/tasks.py
- test.sh
> Vector sources ban raster

- src/layman/geoserver_proxy.py
- src/layman/geoserver_proxy_test.py
- src/layman/layer/__init__.py
- src/layman/layer/filesystem/gdal.py
- src/layman/layer/geoserver/wms.py
- src/layman/layer/rest_workspace_layers_test.py
- src/layman/layer/rest_workspace_test.py
- src/layman/layer/util.py
- src/layman/util.py
- tests/static_publications/single_publication/layers_test.py
- tests/static_publications/single_publication/publications_test.py
> Fix test info

- src/layman/layer/filesystem/input_style.py
- src/layman/layer/filesystem/input_style_test.py
- tests/immutable_endpoints/rest_tools_test.py
> Fix /tools/style-info to return LaymanError for non-parsable XML files

- CHANGELOG.md
- doc/env-settings.md
- src/layman_settings.py
- src/wait_for_deps.py
Part of issue #232
- ~~Tests~~
Optionally
> 232 micka accepted version

- CHANGELOG.md
- src/geoserver/util.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
Part of issue #489
- ~~Tests~~
Optionally
> 489 logging changelog

- .env.demo
- .env.dev
- .env.test
- .gitignore
- CHANGELOG.md
- README.md
- doc/env-settings.md
- src/assert_db.py
- src/clear_layman_data.py
- src/layman/__init__.py
- src/layman/upgrade/upgrade_v1_8.py
- src/layman_flush_redis.py
- src/setup_geoserver.py
- src/wait_for_deps.py
- test_tools/mock/liferay/app.py
- test_tools/mock/micka/app.py
Stop importing layman_settings dynamically
Pycharm autocomplete works for layman.settings
Remove LAYMAN_SETTINGS_MODULE environment variable
- ~~Tests~~
> Stop importing layman_settings dynamically

- src/layman/common/metadata.py
instead the one of EPSG:3857. 
Part of issue #64 
> Metadata extent_equals uses no_area_bbox_padding of EPSG:4326

- CHANGELOG.md
- doc/data-storage.md
- src/layman/layer/filesystem/gdal.py
Part of issue #697 
- ~~Tests~~
Optionally
> Create normalized tif as BigTIFF

- CHANGELOG.md
- src/geoserver/util.py
- src/layman/error_list.py
- src/layman/layer/geoserver/tasks.py
- src/layman/layer/geoserver/util.py
- src/layman/layer/geoserver/wms.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> Raster wrong crs

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_20.py
- src/layman/upgrade/upgrade_v1_20_test.py
> Create new DB column publications.db_connection

- src/layman/layer/db/__init__.py
> 703 Quote identifiers and literals in SQL db/__init__.py

- CHANGELOG.md
- doc/rest.md
- src/db/util.py
- src/layman/layer/db/__init__.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_layers.py
- src/layman/layer/util.py
- src/layman/layer/util_test.py
- test_tools/external_db.py
- test_tools/process_client.py
- tests/dynamic_data/publications/wrong_input/__init__.py
> 703 CRS validations

- src/layman/layer/db/table.py
> Remove `tableowner` from get_layer_info query

- CHANGELOG.md
- doc/rest.md
- docker-compose.demo.yml
- docker-compose.deps.demo.yml
Part of issue #859
- ~~Tests~~
Optionally
> Enable to `host.docker.internal` as alias for localhost for external table URL

- CHANGELOG.md
- doc/models.md
- doc/rest.md
- tests/dynamic_data/publications/layer_timeseries/timeseries_test.py
Part of issue #800 
- ~~Tests~~
> 800 Document that time is always 00:00:00 for timeseries

- src/layman/map/micka/csw.py
- src/layman/map/micka/csw_test.py
- src/layman/map/rest_workspace_test.py
- src/layman/map/util.py
- src/layman/map/util_test.py
- src/layman/upgrade/upgrade_v1_22.py
- tests/asserts/final/publication/internal.py
- tests/asserts/final/publication/metadata.py
- tests/dynamic_data/publications/layer_timeseries/timeseries_test.py
- tests/dynamic_data/publications/map_layer_relation/map_layer_relation.py
Part of issue #868 
- layman.map.rest_workspace_test.test_map_composed_from_local_layers
- static_data
- (COMMON_WORKSPACE, MAP_TYPE, 'post_internal_layer')
- (OWNER, MAP_TYPE, 'post_unauthorized_layer'),
- (OWNER2, LAYER_TYPE, 'post_private_sld2')
> 868 Metadata property operates_on is read from DB

- doc/client-proxy.md
- src/layman/error_list.py
- src/layman/layer/util.py
- src/layman/layer/util_test.py
- src/layman/util.py
- src/layman/util_test.py
> 868 validate x forwarded prefix

- CHANGELOG.md
- src/db/util.py
- src/layman/common/prime_db_schema/schema_initialization.py
- src/layman/geoserver_proxy.py
- src/layman/layer/db/__init__.py
- src/layman/layer/db/table.py
- src/layman/layer/micka/csw.py
- src/layman/layer/prime_db_schema/file_data_tasks.py
- src/layman/layer/prime_db_schema/tasks.py
- src/layman/layer/qgis/wms.py
- src/layman/layer/util.py
- test_tools/external_db.py
- tests/asserts/final/publication/internal.py
- tests/dynamic_data/publications/layer_external_db/edge_db_username_and_password.py
- tests/dynamic_data/publications/layer_external_db/external_db_test.py
- tests/dynamic_data/publications/layer_wfst/new_attribute_test.py
> Use psycopg2.pool

- tests/dynamic_data/publications/map_by_schema_version/exp_2_0_0_map_file.json
- tests/dynamic_data/publications/map_by_schema_version/exp_3_0_0_map_file.json
- tests/dynamic_data/publications/map_by_schema_version/map_test.py
> Fix map_by_schema_version patch test

- tests/dynamic_data/publications/map_layer_relation/map_layer_relation_test.py
- tests/dynamic_data/publications/x_forwarded_prefix/rest_endpoints_test.py
> 868 make some tests optional

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v1_23.py
- src/layman/upgrade/upgrade_v1_23_test.py
- test_tools/process.py
> Add column `role_name` to table `rights`

- CHANGELOG.md
- doc/about.md
- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
- src/layman/common/prime_db_schema/rights.py
- test_tools/process.py
- test_tools/process_client.py
- tests/asserts/util.py
- tests/dynamic_data/publications/access_rights/test_role.py
> On POST/PATCH Workspace Layer/Map insert/update role name to DB

- .env.demo
- .env.dev
- .env.test
- CHANGELOG.md
- doc/env-settings.md
- src/layman/authz/role_service.py
- src/layman_settings.py
> Create and use LAYMAN_ROLE_SERVICE_URI env

- CHANGELOG.md
- src/layman/common/geoserver/__init__.py
- src/layman/common/geoserver/geoserver_test.py
- src/layman/layer/geoserver/__init__.py
- src/layman/layer/geoserver/wfs.py
- src/layman/layer/geoserver/wms.py
- tests/asserts/final/publication/geoserver_proxy.py
- tests/asserts/final/publication/geoserver_util.py
- tests/dynamic_data/publications/access_rights/test_access_rights_application.py
- tests/dynamic_data/publications/access_rights/test_role.py
- tests/static_data/single_publication/layers_test.py
- tests/static_data/single_publication/publications_test.py
> Test access right roles in GeoServer

- .env.test
- Makefile
- src/drop_layman_role_service_schema.py
- src/layman/__init__.py
- src/layman/upgrade/upgrade_v1_23.py
> Drop role service DB schema before tests

- src/layman/common/prime_db_schema/publications.py
- src/layman/common/prime_db_schema/publications_test.py
> i_can_still_write respects role of the user

- .env.dev
- .env.test
- src/layman/upgrade/upgrade_v1_23.py
- src/layman/upgrade/upgrade_v1_23_test.py
- src/setup_geoserver.py
> (Re)create only necessary views and tables in upgrade_v1_23.py

- CHANGELOG.md
- README.md
- doc/data-storage.md
- doc/env-settings.md
- doc/models.md
- doc/rest.md
- doc/security.md
> Document role service

- doc/env-settings.md
> Document JDBC role service password stored as plaintext

- .remarkrc
- CHANGELOG.md
- doc/rest.md
- src/layman/layer/__init__.py
- src/layman/layer/rest_workspace_layer.py
- src/layman/layer/rest_workspace_test.py
- src/layman/map/__init__.py
- src/layman/map/rest_workspace_map.py
- src/layman/map/rest_workspace_test.py
- test_tools/process_client.py
> PATCH Workspace Layer returns only short response

- CHANGELOG.md
- src/layman/upgrade/__init__.py
- src/layman/upgrade/upgrade_v2_0.py
- src/layman/upgrade/upgrade_v2_0_test.py
> Migrate description into prime_db

- tests/dynamic_data/users_roles/delete_user_test.py
Part of issue #161
- ~~[ ] Changelog~~
> 161 add ids to indirect pytest parametrizations
